// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znttfsjthhctjshhyzlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpudHRmc2p0aGhjdGpzaGh5emxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzMyNDgsImV4cCI6MjA2NjkwOTI0OH0.NLGC8Jk0BRDWHE3sX8E8dwM1n9mm7CvqNkjT3MjHBss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});